describe("jq ffi", function()
  describe("module", function()
    local jq = require "resty.jq"
    it("has a _VERSION", function()
      assert.is_string(jq._VERSION)
    end)

    it("has expected methods", function()
      assert.is_function(jq.new)
      assert.is_function(jq.teardown)
      assert.is_function(jq.compile)
      assert.is_function(jq.filter)
    end)
  end)

  describe("initialisation", function()
    local jq, err = require("resty.jq").new()

    it("creates new context", function()
      assert.truthy(jq)
      assert.is_nil(err)
    end)

    it("tears down context", function()
      jq:teardown()

      local res, err = jq:compile(".")
      assert.falsy(res)
      assert.same("not initialized", err)

      local jq, err = require("resty.jq").new()
      local res, err = jq:compile(".")
      assert.truthy(res)
      assert.is_nil(err)

      jq:teardown()

      local res, err = jq:filter("[]")
      assert.falsy(res)
      assert.same("not initialized", err)
    end)
  end)

  describe("compilation", function()
    it("fails to compile a bad program", function()
      local jq, err = require("resty.jq").new()
      local res, err = jq:compile(".[")
      assert.falsy(res)
      assert.same("compilation failed", err)
    end)

    it("refuses to filter an uncompiled program", function()
      local jq, err = require("resty.jq").new()
      local res, err = jq:filter("[]")
      assert.falsy(res)
      assert.same("unable to filter: program was not compiled", err)
    end)

    it("compiles a valid program", function()
      local jq, err = require("resty.jq").new()
      local res, err = jq:compile(".")
      assert.truthy(res)
      assert.is_nil(err)
    end)
  end)

  describe("filter", function()
    local jq, err = require("resty.jq").new()
    local res, err = jq:compile(".foo")

    it("fails to filter with bad options", function()
      local res, err = jq:filter("[]", { dump = "" })
      assert.same(err, "invalid option: dump")
      assert.falsy(res)

      local res, err = jq:filter("[]", { flags = "" })
      assert.same(err, "invalid option: flags")
      assert.falsy(res)

      local res, err = jq:filter("[]", { raw = "" })
      assert.same(err, "invalid option: raw")
      assert.falsy(res)

      local res, err = jq:filter("[]", { join = "" })
      assert.same(err, "invalid option: join")
      assert.falsy(res)
    end)

    it("fails to filter with bad input", function()
      local res, err = jq:filter("[")
      assert.same(err, "unable to filter: parse failed")
      assert.falsy(res)
    end)

    it("filters with good input", function()
      local res, err = jq:filter([[{"foo": 42, "bar": "less interesting data"}]])
      assert.truthy(res)
      assert.is_nil(err)
      assert.same("42\n", res)
    end)
  end)

  describe("options", function()
    local jq, err = require("resty.jq").new()
    local res, err = jq:compile(".foo")

    it("filters with raw option", function()
      local res, err = jq:filter([[{"foo": "bar"}]], { raw = false })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("\"bar\"\n", res)

      local res, err = jq:filter([[{"foo": "bar"}]], { raw = true })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("bar\n", res)
    end)

    it("filters with join option", function()
      local res, err = jq:filter([[{"foo": "bar"}]], { join = false })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("\"bar\"\n", res)

      local res, err = jq:filter([[{"foo": "42"}]], { join = true })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("42", res)
    end)

    it("filters with dump option", function()
      local res, err = jq:filter([[{"foo": "bar"}]], { dump = 0 })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("\"bar\"\n", res)

      local res, err = jq:filter([[{"foo": "bar"}]], { dump = 2 })
      assert.is_nil(err)
      assert.truthy(res)
      assert.same("\"bar\"\n", res)
    end)
  end)
end)
