name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "luajit-openresty"
      - uses: leafo/gh-actions-luarocks@v6
        with:
          luaRocksVersion: "3.13.0"
      - run: sudo apt-get update
      - run: sudo apt-get install -y libjq-dev
      - run: luarocks install luacheck
      - run: luarocks install luacov
      - run: luarocks install busted
      - run: luarocks make
      - run: make lint
      - run: make coverage
      - run: sudo apt-get install -y valgrind
      - name: memory check (valgrind)
        run: >-
          valgrind --leak-check=full --error-exitcode=99 --trace-children=yes
          busted -o gtest --lua="$(command -v luajit)"
