name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit-2.0.5"
      - uses: leafo/gh-actions-luarocks@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y libjq-dev
      - run: luarocks install luacheck
      - run: luarocks install luacov
      - run: luarocks install busted
      - run: make all
