name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: "luajit-2.1"
      - uses: luarocks/gh-actions-luarocks@master
        with:
          luaRocksVersion: "@418d2ab34891b130cc317df32f65f978640febcf"
      - run: sudo apt-get update
      - run: sudo apt-get install -y libjq-dev
      - run: luarocks install luacheck
      - run: luarocks install luacov
      - run: luarocks install busted
      - run: luarocks make
      - run: make lint
      - run: make coverage
